import StyleDictionary from 'style-dictionary'
import { Register, TransformedToken } from 'style-dictionary/types'

// Strip "px" and return a number — MUI spacing/fontSize expects numbers
const pxToNumber = (value: string) => parseFloat(value)

const sd = new StyleDictionary({
  source: ['tokens-source/tokens.json'],
  platforms: {
    ts: {
      transformGroup: 'js',
      buildPath: 'src/tokens/generated/',
      transforms: ['name/camel'],
      files: [
        {
          destination: 'colors.ts',
          format: 'javascript/esm',
          filter: (token: TransformedToken) => token.path[0] === 'color',
        },
        {
          destination: 'typography.ts',
          format: 'javascript/esm',
          filter: (token: TransformedToken) => token.path[0] === 'typography',
        },
        {
          destination: 'spacing.ts',
          format: 'javascript/esm',
          filter: (token: TransformedToken) => token.path[0] === 'spacing',
        },
        {
          destination: 'shadows.ts',
          format: 'javascript/esm',
          filter: (token: TransformedToken) => token.path[0] === 'shadow',
        },
      ],
    },
  },
})

// Register ESM format
StyleDictionary.registerFormat({
  name: 'javascript/esm',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens
      .map((token) => `export const ${token.name} = ${JSON.stringify(token.$value ?? token.value)};`)
      .join('\n')
    return `// Auto-generated by Style Dictionary — do not edit manually\n${tokens}\n`
  },
})

export default sd
