import { createTheme } from '@mui/material/styles'

// These are generated by Style Dictionary from tokens-source/tokens.json
// Run `npm run build:tokens` to regenerate after updating tokens
import * as colors from '../tokens/generated/colors'
import * as typography from '../tokens/generated/typography'
import * as spacing from '../tokens/generated/spacing'
import * as shadows from '../tokens/generated/shadows'

export const theme = createTheme({
  palette: {
    primary: { main: colors.colorBrandPrimary },
    secondary: { main: colors.colorBrandSecondary },
    error: { main: colors.colorSemanticError },
    warning: { main: colors.colorSemanticWarning },
    success: { main: colors.colorSemanticSuccess },
    info: { main: colors.colorSemanticInfo },
    background: { default: colors.colorNeutral100 },
    text: { primary: colors.colorNeutral900 },
  },
  typography: {
    fontFamily: typography.typographyFontFamilyBase,
    fontSize: 16,
    h1: { fontSize: typography.typographyFontSize3xl, fontWeight: typography.typographyFontWeightBold },
    h2: { fontSize: typography.typographyFontSize2xl, fontWeight: typography.typographyFontWeightSemibold },
    h3: { fontSize: typography.typographyFontSizeXl, fontWeight: typography.typographyFontWeightSemibold },
    h4: { fontSize: typography.typographyFontSizeLg, fontWeight: typography.typographyFontWeightMedium },
    body1: { fontSize: typography.typographyFontSizeMd },
    body2: { fontSize: typography.typographyFontSizeSm },
    caption: { fontSize: typography.typographyFontSizeXs },
  },
  shadows: [
    'none',
    shadows.shadowSm,
    shadows.shadowMd,
    shadows.shadowLg,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
    shadows.shadowXl,
  ],
})
